name: flutter_library_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  fl_chart: ^1.0.0
  image_picker: ^1.2.0
  table_calendar: ^3.2.0
  path_provider: ^2.1.5
  http: ^1.5.0
  mobile_scanner: ^7.0.1
  google_sign_in: ^6.1.0
  sign_in_button: ^4.0.1
  cloud_firestore: ^6.0.0
  hive:  ^2.2.3
  hive_flutter: ^1.1.0
  firebase_storage: ^13.0.0
  connectivity_plus: ^6.1.5
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  mocktail: ^1.0.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/cover.jpg
    - assets/coverNotAvailable.jpeg