// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaHY8GFrNv4WMzdY7rgm3IcNY296uKKiE',
    appId: '1:812531422229:web:d077f6673f6ef4e8bfaa1c',
    messagingSenderId: '812531422229',
    projectId: 'trackmyread-b87be',
    authDomain: 'trackmyread-b87be.firebaseapp.com',
    storageBucket: 'trackmyread-b87be.firebasestorage.app',
    measurementId: 'G-KCGTP3YG4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7sEmUzhhi0qeJ1cIu6kpR1apAlsAejI',
    appId: '1:812531422229:android:3e3f18d4ca24ad20bfaa1c',
    messagingSenderId: '812531422229',
    projectId: 'trackmyread-b87be',
    storageBucket: 'trackmyread-b87be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFwn6k1EsXxTLVAHbCWM1HBdupxdfcp8',
    appId: '1:812531422229:ios:6826f02c5a305323bfaa1c',
    messagingSenderId: '812531422229',
    projectId: 'trackmyread-b87be',
    storageBucket: 'trackmyread-b87be.firebasestorage.app',
    androidClientId: '812531422229-796smafgue8511kcgmnm37q0710vv91p.apps.googleusercontent.com',
    iosClientId: '812531422229-j3t1lf783jhh5fvpc8p9j6rqidgine07.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLibraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxFwn6k1EsXxTLVAHbCWM1HBdupxdfcp8',
    appId: '1:812531422229:ios:6826f02c5a305323bfaa1c',
    messagingSenderId: '812531422229',
    projectId: 'trackmyread-b87be',
    storageBucket: 'trackmyread-b87be.firebasestorage.app',
    androidClientId: '812531422229-796smafgue8511kcgmnm37q0710vv91p.apps.googleusercontent.com',
    iosClientId: '812531422229-j3t1lf783jhh5fvpc8p9j6rqidgine07.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLibraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaHY8GFrNv4WMzdY7rgm3IcNY296uKKiE',
    appId: '1:812531422229:web:7f8d0089ea78b811bfaa1c',
    messagingSenderId: '812531422229',
    projectId: 'trackmyread-b87be',
    authDomain: 'trackmyread-b87be.firebaseapp.com',
    storageBucket: 'trackmyread-b87be.firebasestorage.app',
    measurementId: 'G-KNZ699Q61T',
  );
}
